from locust import HttpUser, task, between

class AppRunnerLoadTest(HttpUser):
    # Time between tasks — set to 0 for pure concurrency
    host = "https://4uhm6b5y9e.us-west-2.awsapprunner.com"
    wait_time = between(0, 0)

    @task
    def post_generate_mcq(self):
        headers = {"Content-Type": "application/json"}
        payload = {
            "text": """
            Keystroke data collected through web applications offers a granular, real-time record of typing behavior, making it a valuable resource for analyzing writing processes. However, raw keystroke logs are inherently complex and often contain inconsistencies and system-generated artifacts, such as keyboard shortcuts, automated corrections, or unintended keystrokes, which can obscure meaningful patterns if not properly addressed. Thus, effective preprocessing is essential to ensure the reliability and interpretability of the data. 

            A fundamental step in keystroke data preprocessing may involve identifying and filtering out irrelevant or erroneous keystrokes, such as those resulting from system-generated events or accidental key presses. For instance, rapid successive deletions or repeated character insertions may indicate typing errors rather than meaningful text production. Additionally, in cases where writers compose text across multiple devices or applications, timestamp normalization is critical to mitigate discrepancies in system clock accuracy and variations in logging intervals. Without proper alignment, differences in timestamp resolution across devices may introduce inconsistencies in the measurement of typing speed and pause durations, potentially skewing analyses of writing dynamics. Another challenge in keystroke data preprocessing involves handling missing or incomplete data, which can arise due to logging interruptions or device switching. Such gaps in keystroke sequences may disrupt the continuity of recorded writing behaviors, making it difficult to accurately reconstruct the writing process. To address this, missing data can be managed through imputation techniques, such as statistical interpolation or predictive modeling, to estimate missing keystrokes based on surrounding input patterns. These methods help preserve the integrity of keystroke sequences while minimizing distortions in writing behavior analysis.

            Keystroke Measures.  

            By implementing effective preprocessing techniques, researchers can transform raw keystroke logs into structured, high-quality datasets that facilitate robust analyses of writing behavior and cognitive processes using a variety of keystroke measures. Thus far, the most frequently used keystroke measures in applied linguistics are those regarding pauses, revisions, and bursts. 

            Pauses. A key feature of keystroke logging is its ability to accurately record the timing of individual keystrokes, enabling the calculation of inter-keystroke intervals (IKI). IKI is defined as the time elapsed between two consecutive key presses, typically measured in milliseconds (Chukharev-Hudilainen et al., 2019). For example, consider a scenario in which a writer presses the key for the letter "A" at a specific timestamp, T1​, followed by the key for the letter "B" at a subsequent timestamp, T2​. The interval between these two actions, calculated as IKI = T1  T2, represents the temporal gap between key presses.

            Given the physical and motor limitations inherent in human typing, not all IKIs can be interpreted as pauses. To address this, researchers typically adopt specific thresholds to classify IKIs as pauses. Limpo and Alvès (2017) highlight two widely used thresholds in the field: short pauses are typically defined as IKIs ranging from approximately 30 milliseconds to 2 seconds, while long pauses are defined as those exceeding 2 seconds. The selection of an IKI threshold, however, often depends on the specific objectives and context of the study. For instance, the 2-second threshold has been frequently employed in studies of writing processes (e.g., Spelman Miller, 2000; Sullivan & Lindgren, 2002; Wengelin, 2001). Van Waes and Schellens (2003), however, utilized a threshold of 3 seconds. This higher threshold allowed them to distinguish more clearly between different pausing patterns among adult writers.

            Despite varied defining thresholds, pause behaviors are typically operationalized through the duration and frequency of pauses (e.g., Medimorec & Risko, 2016; Van Waes & Schellens, 2003; Van Waes et al., 2014). Commonly used metrics include the total number of pauses, the frequency of pauses per minute or per 100 words, the proportion of time spent pausing relative to total writing time, and the average duration of pauses during text production. Moreover, researchers have also examined how the duration and frequency of pauses may vary at different locations in a text (e.g., within words, between words, between sentences). Such location-specific analyses are crucial for understanding how writers allocate cognitive resources during different phases of text construction.

            Revision. Revision in writing refers to the processes of modifying a text by making deletions or insertions (Spelman Miller et al., 2008). Specifically, an insertion involves a series of operations that add characters within an existing text while a deletion refers to the removal of any sequence of characters (Perrin, 2019). Keystroke logging offers a powerful means to capture and analyze these revision behaviors during the process of text production, including the text that is deleted, inserted, or replaced as well as the precise timestamps and locations of these revision events. This enables researchers to observe and analyze revising behaviors from multiple dimensions. 

            \tSome general measures can be easily obtained from keystroke data to provide insights into the overall extent of revision activity. These include the total number of deletions and insertions (Spelman Miller et al., 2008) or the frequency of these revisions per minute (Van Waes & Leijten, 2015). Keystroke logging also enables the extraction of more fine-grained revision metrics by leveraging cursor position information. For instance, researchers can classify revisions based on their location within the text, such as revisions at the point of inscription where the writer is actively extending the text or at a previous point in the text after the text has been transcribed (Stevenson et al., 2006). Cursor position information also enables the calculation of the distance between the flashing cursor's position and the revision point, offering additional insights into writers' behavior. Thorson (2000), for example, utilized this approach to distinguish between immediate revisions, which occur at the current cursor location, and distant revisions, where the cursor is moved to another part of the text for modifications. 

            \tMoreover, by tracking the changes to the text throughout the process using keystroke logging, researchers can categorize revisions based on the writer's underlying intentions, such as content revisions, language revisions, and typographic revisions (Stevenson et al., 2006). Specifically, content revisions involve changes that alter the meaning or substance of the text. For example, modifying the sentence "She is a teacher" to "She is a student" reflects a shift in the conveyed information. Language revisions, on the other hand, focus on surface-level modifications that do not affect the underlying meaning of the text. These include correcting errors in spelling, grammar, or punctuation, as well as rephrasing for stylistic or clarity purposes. For instance, changing "She is not happy" to "She is unhappy" retains the same semantic meaning while improving linguistic expression. Lastly, typographic revisions address errors arising from unintentional keystrokes, such as accidentally pressing incorrect keys. These revisions are often mechanical in nature, reflecting the motor aspects of typing rather than cognitive or linguistic considerations.

            Bursts. Keystroke logging provides researchers with the ability to identify and analyze periods of uninterrupted text production, during which writers produce stretches of text without pauses or revisions. These continuous segments are commonly referred to as bursts (Kaufer et al., 1986). Bursts stand in contrast to the disfluent aspects of writing, which are characterized by frequent pauses and revisions. Instead, they reflect the fluent and productive phases of text generation, where ideas flow relatively seamlessly into written form. Hence, burst-related features have been widely used as measures of writing fluency in research (e.g., Spelman Miller et al., 2008; Van Waes & Leijten, 2015).  
            """,
            "fact": 3,
            "inference": 3,
            "main_idea": 1,
            "quality_first": "no"
        }

        # Send POST request
        self.client.post("/generate_mcq", json=payload, headers=headers)

